Done modifications
srbcheema1/my_scripts pull request #50
Opened 2018-05-04 07:44 UTC by Rohithgilla12

2018-05-04 07:58 UTC, Rohithgilla12 commented
Btw I have updated the readme file and added badeges should i pr that?

2018-05-04 16:32 UTC, srbcheema1 requested changes

2018-05-04 16:32 UTC, srbcheema1 commented on xkcd.py
> +l=[] #For storing random numbers
Why to declare it so earlier ? it should be near the code it is being used in.
Actually I am not gonna use it in the code(read my next comment for followup). Just telling to declare variables close to the code block they are used in, unless they are used at many places.

2018-05-04 16:32 UTC, srbcheema1 commented on xkcd.py
> +for i in range(choice):
there is no need of this loop and no need of `l=[]`
you could simply generate a random number on the go.

2018-05-04 16:32 UTC, srbcheema1 commented on xkcd.py
> +for i in l:
do this as
```
for i in range(choice):
   num = str(random.randint(1,1933))
   url = "http://xkcd.com/"+num+"/"
```

2018-05-04 16:32 UTC, srbcheema1 commented on README.md
> +
thanks for this :)
it looks great

2018-05-04 16:32 UTC, srbcheema1 commented on CricketNotifications.py
> +
remove this empty line

2018-05-04 16:33 UTC, srbcheema1 commented
I have requested small changes.
After this I will merge this PR
also thanks for the README update.
it really looks nice :smiley:

2018-05-04 17:52 UTC, Rohithgilla12 commented
Done modifications :D

2018-05-05 19:51 UTC, srbcheema1 commented
looks good to me now :relaxed:

2018-05-05 20:01 UTC, srbcheema1 approved these changes
just one last thing before we merge this PR.you may sqash all those commits into one commit. this is optional and its your wish. you will learn a cool thing that is highly useful in open source. I am happy with the PR. just you may do it if you want else . tell me if you are going to squash them into one. otherwise its fine . i will be waiting to merge it :)

2018-05-06 04:34 UTC, Rohithgilla12 commented
Hey how to squash all commits into one, I tried but i didn't understand the way.
Can you help me in that please

2018-05-06 05:48 UTC, Rohithgilla12 commented
Yeah, Dude merge it now :)

2018-05-06 08:24 UTC, merged

2018-05-06 08:26 UTC, srbcheema1 commented
Merged :)
You may now have a look at https://github.com/srbcheema1/CheemaFy
this is my favourite repository.
If you use ubuntu you will surely like it

2018-05-06 19:04 UTC, Rohithgilla12 commented
I use a Mac.
I'll see it and try to contribute to it :)

2018-05-06 19:07 UTC, srbcheema1 commented
I have recently added support for mac. but thats in alpha state. i m working on that too.